#!/usr/bin/env python3
"""
Generate a standalone HTML report from verbench JSON output.

Usage:
    python3 tools/verbench/report.py [perf_by_version.json] [out.html]

The generated HTML is self-contained: no Docker, database, Grafana, CDN or
JavaScript dependency is required. Charts are emitted as inline SVG.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import math
from pathlib import Path
from typing import Iterable


METRICS = ("l2_ns", "l3_ns", "l4_ns", "l7_ns", "total_ns")
LAYERS = ("l2_ns", "l3_ns", "l4_ns", "l7_ns")
COLORS = {
    "l2_ns": "#2563eb",
    "l3_ns": "#059669",
    "l4_ns": "#d97706",
    "l7_ns": "#dc2626",
    "total_ns": "#111827",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a standalone HTML report from perf_by_version.json.",
    )
    parser.add_argument(
        "input",
        nargs="?",
        help="Input JSON generated by tools/verbench/run.sh.",
    )
    parser.add_argument(
        "output",
        nargs="?",
        help="Output HTML path. Defaults to input path with .html suffix.",
    )
    return parser.parse_args()


def default_input_path() -> Path:
    return Path(__file__).resolve().parents[2] / "perf_by_version.json"


def version_sort_key(label: str) -> tuple[tuple[int, int, int], int, str]:
    base, sep, suffix = label.partition("-")
    nums = []
    for part in base.split("."):
        try:
            nums.append(int(part))
        except ValueError:
            nums.append(0)
    while len(nums) < 3:
        nums.append(0)

    # Keep the local build after the matching published version.
    suffix_order = 1 if sep else 0
    return (tuple(nums[:3]), suffix_order, suffix)


def load_results(path: Path) -> list[dict[str, int | str]]:
    with path.open("r", encoding="utf-8") as f:
        raw = json.load(f)

    if not isinstance(raw, dict):
        raise ValueError("expected a JSON object: {version: timing}")

    rows: list[dict[str, int | str]] = []
    for version, timings in raw.items():
        if not isinstance(timings, dict):
            raise ValueError(f"invalid timing payload for {version!r}")
        row: dict[str, int | str] = {"version": str(version)}
        for metric in METRICS:
            if metric not in timings:
                raise ValueError(f"missing {metric!r} for {version!r}")
            row[metric] = int(timings[metric])
        rows.append(row)

    rows.sort(key=lambda row: version_sort_key(str(row["version"])))
    return rows


def derived_output_path(input_path: Path) -> Path:
    if input_path.suffix:
        return input_path.with_suffix(".html")
    return input_path.with_name(input_path.name + ".html")


def pct(delta: int, base: int) -> float:
    if base == 0:
        return 0.0
    return (delta / base) * 100.0


def signed_ns(value: int) -> str:
    if value > 0:
        return f"+{value} ns"
    return f"{value} ns"


def signed_pct(value: float) -> str:
    if value > 0:
        return f"+{value:.2f}%"
    return f"{value:.2f}%"


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def polyline(points: Iterable[tuple[float, float]]) -> str:
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in points)


def chart_ticks(max_value: int, count: int = 5) -> list[int]:
    if max_value <= 0:
        return [0]
    raw_step = max_value / max(count - 1, 1)
    magnitude = 10 ** math.floor(math.log10(raw_step))
    normalized = raw_step / magnitude
    if normalized <= 1:
        step = magnitude
    elif normalized <= 2:
        step = 2 * magnitude
    elif normalized <= 5:
        step = 5 * magnitude
    else:
        step = 10 * magnitude
    top = int(math.ceil(max_value / step) * step)
    return [int(i * step) for i in range(int(top / step) + 1)]


def line_chart(
    rows: list[dict[str, int | str]],
    metric_names: tuple[str, ...],
    title: str,
) -> str:
    width = 980
    height = 360
    left = 66
    right = 22
    top = 36
    bottom = 82
    inner_w = width - left - right
    inner_h = height - top - bottom

    max_value = max(int(row[m]) for row in rows for m in metric_names)
    ticks = chart_ticks(max_value)
    y_max = max(ticks[-1], 1)

    def x_at(index: int) -> float:
        if len(rows) == 1:
            return left + inner_w / 2
        return left + (index * inner_w / (len(rows) - 1))

    def y_at(value: int) -> float:
        return top + inner_h - ((value / y_max) * inner_h)

    parts = [
        f'<svg class="chart" viewBox="0 0 {width} {height}" role="img" '
        f'aria-label="{esc(title)}">',
        f'<text x="{left}" y="22" class="chart-title">{esc(title)}</text>',
    ]

    for tick in ticks:
        y = y_at(tick)
        parts.append(f'<line x1="{left}" y1="{y:.1f}" x2="{width-right}" y2="{y:.1f}" class="grid"/>')
        parts.append(f'<text x="{left-10}" y="{y+4:.1f}" text-anchor="end" class="axis">{tick}</text>')

    for i, row in enumerate(rows):
        x = x_at(i)
        parts.append(f'<line x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{top+inner_h}" class="xgrid"/>')
        parts.append(
            f'<text x="{x:.1f}" y="{height-34}" text-anchor="end" '
            f'transform="rotate(-35 {x:.1f} {height-34})" class="axis">'
            f'{esc(row["version"])}</text>'
        )

    parts.append(f'<line x1="{left}" y1="{top+inner_h}" x2="{width-right}" y2="{top+inner_h}" class="axis-line"/>')
    parts.append(f'<line x1="{left}" y1="{top}" x2="{left}" y2="{top+inner_h}" class="axis-line"/>')

    legend_x = width - right - 320
    for offset, metric in enumerate(metric_names):
        color = COLORS[metric]
        lx = legend_x + offset * 80
        parts.append(f'<line x1="{lx}" y1="20" x2="{lx+18}" y2="20" stroke="{color}" stroke-width="3"/>')
        parts.append(f'<text x="{lx+24}" y="24" class="legend">{esc(metric.replace("_ns", ""))}</text>')

    for metric in metric_names:
        color = COLORS[metric]
        points = [(x_at(i), y_at(int(row[metric]))) for i, row in enumerate(rows)]
        parts.append(
            f'<polyline fill="none" stroke="{color}" stroke-width="3" '
            f'stroke-linejoin="round" stroke-linecap="round" points="{polyline(points)}"/>'
        )
        for i, row in enumerate(rows):
            value = int(row[metric])
            x, y = x_at(i), y_at(value)
            parts.append(f'<circle cx="{x:.1f}" cy="{y:.1f}" r="3.5" fill="{color}">')
            parts.append(f"<title>{esc(row['version'])} - {esc(metric)}: {value} ns</title>")
            parts.append("</circle>")

    parts.append("</svg>")
    return "\n".join(parts)


def delta_chart(rows: list[dict[str, int | str]]) -> str:
    width = 980
    height = 320
    left = 66
    right = 22
    top = 36
    bottom = 82
    inner_w = width - left - right
    inner_h = height - top - bottom

    deltas = [0]
    for previous, current in zip(rows, rows[1:]):
        previous_total = int(previous["total_ns"])
        current_total = int(current["total_ns"])
        deltas.append(current_total - previous_total)

    max_abs = max(max(abs(v) for v in deltas), 1)
    y_min = -max_abs
    y_max = max_abs

    def x_at(index: int) -> float:
        return left + (index * inner_w / len(rows))

    def y_at(value: int) -> float:
        return top + inner_h - (((value - y_min) / (y_max - y_min)) * inner_h)

    baseline = y_at(0)
    bar_w = max(6.0, inner_w / len(rows) * 0.62)
    parts = [
        f'<svg class="chart" viewBox="0 0 {width} {height}" role="img" '
        'aria-label="Delta total_ns vs previous version">',
        f'<text x="{left}" y="22" class="chart-title">Delta total_ns vs version precedente</text>',
        f'<line x1="{left}" y1="{baseline:.1f}" x2="{width-right}" y2="{baseline:.1f}" class="axis-line"/>',
        f'<text x="{left-10}" y="{baseline+4:.1f}" text-anchor="end" class="axis">0</text>',
        f'<text x="{left-10}" y="{top+4}" text-anchor="end" class="axis">+{max_abs}</text>',
        f'<text x="{left-10}" y="{top+inner_h}" text-anchor="end" class="axis">-{max_abs}</text>',
    ]

    for i, (row, delta) in enumerate(zip(rows, deltas)):
        x = x_at(i) + (inner_w / len(rows) - bar_w) / 2
        y = y_at(max(delta, 0))
        h = abs(y_at(delta) - baseline)
        color = "#b91c1c" if delta > 0 else "#047857"
        if delta == 0:
            color = "#6b7280"
            h = 2
            y = baseline - 1
        parts.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_w:.1f}" height="{h:.1f}" fill="{color}">')
        parts.append(f"<title>{esc(row['version'])}: {signed_ns(delta)}</title>")
        parts.append("</rect>")
        label_x = x + bar_w / 2
        parts.append(
            f'<text x="{label_x:.1f}" y="{height-34}" text-anchor="end" '
            f'transform="rotate(-35 {label_x:.1f} {height-34})" class="axis">'
            f'{esc(row["version"])}</text>'
        )

    parts.append(f'<line x1="{left}" y1="{top}" x2="{left}" y2="{top+inner_h}" class="axis-line"/>')
    parts.append("</svg>")
    return "\n".join(parts)


def summary_cards(rows: list[dict[str, int | str]]) -> str:
    first = rows[0]
    last = rows[-1]
    fastest = min(rows, key=lambda row: int(row["total_ns"]))

    published = [row for row in rows if not str(row["version"]).endswith("-local")]
    latest_published = published[-1] if published else last
    local = next((row for row in reversed(rows) if str(row["version"]).endswith("-local")), None)

    first_total = int(first["total_ns"])
    last_total = int(last["total_ns"])
    overall_delta = last_total - first_total

    local_text = "Pas de build local dans le JSON."
    local_class = "neutral"
    if local:
        local_total = int(local["total_ns"])
        base_total = int(latest_published["total_ns"])
        delta = local_total - base_total
        local_text = (
            f"{esc(local['version'])} vs {esc(latest_published['version'])}: "
            f"{signed_ns(delta)} ({signed_pct(pct(delta, base_total))})"
        )
        local_class = "good" if delta <= 0 else "bad"

    return f"""
    <section class="cards">
      <article class="card">
        <span>Versions mesurees</span>
        <strong>{len(rows)}</strong>
        <small>{esc(first['version'])} -> {esc(last['version'])}</small>
      </article>
      <article class="card">
        <span>Plus rapide</span>
        <strong>{esc(fastest['version'])}</strong>
        <small>{fastest['total_ns']} ns total</small>
      </article>
      <article class="card">
        <span>Evolution globale</span>
        <strong class="{('good' if overall_delta <= 0 else 'bad')}">{signed_ns(overall_delta)}</strong>
        <small>{signed_pct(pct(overall_delta, first_total))}</small>
      </article>
      <article class="card">
        <span>Local</span>
        <strong class="{local_class}">{local_text}</strong>
        <small>Compare au dernier publish mesure</small>
      </article>
    </section>
    """


def findings(rows: list[dict[str, int | str]]) -> str:
    pairs = list(zip(rows, rows[1:]))
    if not pairs:
        return ""

    changes = []
    for previous, current in pairs:
        previous_total = int(previous["total_ns"])
        current_total = int(current["total_ns"])
        delta = current_total - previous_total
        changes.append((delta, previous, current))

    best = min(changes, key=lambda item: item[0])
    worst = max(changes, key=lambda item: item[0])

    best_delta, best_prev, best_cur = best
    worst_delta, worst_prev, worst_cur = worst

    return f"""
    <section class="panel">
      <h2>Points notables</h2>
      <ul class="findings">
        <li><strong>Meilleur gain:</strong> {esc(best_prev['version'])} -> {esc(best_cur['version'])},
          {signed_ns(best_delta)} ({signed_pct(pct(best_delta, int(best_prev['total_ns'])))})</li>
        <li><strong>Plus forte regression:</strong> {esc(worst_prev['version'])} -> {esc(worst_cur['version'])},
          {signed_ns(worst_delta)} ({signed_pct(pct(worst_delta, int(worst_prev['total_ns'])))})</li>
      </ul>
    </section>
    """


def result_table(rows: list[dict[str, int | str]]) -> str:
    body = []
    previous_total: int | None = None
    for row in rows:
        total = int(row["total_ns"])
        if previous_total is None:
            delta = ""
            delta_class = "neutral"
        else:
            diff = total - previous_total
            delta = f"{signed_ns(diff)} ({signed_pct(pct(diff, previous_total))})"
            delta_class = "good" if diff <= 0 else "bad"
        previous_total = total

        body.append(
            "<tr>"
            f"<td>{esc(row['version'])}</td>"
            f"<td>{row['l2_ns']}</td>"
            f"<td>{row['l3_ns']}</td>"
            f"<td>{row['l4_ns']}</td>"
            f"<td>{row['l7_ns']}</td>"
            f"<td><strong>{row['total_ns']}</strong></td>"
            f'<td class="{delta_class}">{esc(delta)}</td>'
            "</tr>"
        )

    return """
    <section class="panel">
      <h2>Donnees detaillees</h2>
      <div class="table-wrap">
        <table>
          <thead>
            <tr>
              <th>Version</th>
              <th>L2 ns</th>
              <th>L3 ns</th>
              <th>L4 ns</th>
              <th>L7 ns</th>
              <th>Total ns</th>
              <th>Delta total</th>
            </tr>
          </thead>
          <tbody>
            %s
          </tbody>
        </table>
      </div>
    </section>
    """ % "\n".join(body)


def render_html(rows: list[dict[str, int | str]], input_path: Path) -> str:
    generated_at = dt.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")
    payload = {
        str(row["version"]): {metric: int(row[metric]) for metric in METRICS}
        for row in rows
    }
    raw_json = json.dumps(payload, indent=2)

    return f"""<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>packet_parser - rapport verbench</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f8fafc;
      --panel: #ffffff;
      --ink: #111827;
      --muted: #667085;
      --line: #d0d5dd;
      --soft: #eef2f7;
      --good: #047857;
      --bad: #b91c1c;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font: 14px/1.5 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    main {{ max-width: 1180px; margin: 0 auto; padding: 32px 24px 48px; }}
    header {{ margin-bottom: 22px; }}
    h1 {{ margin: 0 0 6px; font-size: 30px; line-height: 1.1; letter-spacing: 0; }}
    h2 {{ margin: 0 0 16px; font-size: 18px; letter-spacing: 0; }}
    p {{ margin: 0; color: var(--muted); }}
    code {{ background: var(--soft); padding: 2px 5px; border-radius: 4px; }}
    .cards {{
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 12px;
      margin: 22px 0;
    }}
    .card, .panel {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      box-shadow: 0 1px 2px rgba(16, 24, 40, 0.04);
    }}
    .card {{ padding: 16px; min-height: 118px; }}
    .card span {{ display: block; color: var(--muted); font-size: 12px; text-transform: uppercase; }}
    .card strong {{ display: block; margin-top: 8px; font-size: 22px; line-height: 1.2; }}
    .card small {{ display: block; margin-top: 8px; color: var(--muted); }}
    .panel {{ padding: 18px; margin-top: 16px; overflow: hidden; }}
    .chart {{ width: 100%; height: auto; display: block; }}
    .chart-title {{ font-size: 15px; font-weight: 700; fill: var(--ink); }}
    .grid {{ stroke: #d9e0ea; stroke-width: 1; }}
    .xgrid {{ stroke: #eef2f7; stroke-width: 1; }}
    .axis-line {{ stroke: #98a2b3; stroke-width: 1.2; }}
    .axis, .legend {{ font-size: 11px; fill: #475467; }}
    .findings {{ margin: 0; padding-left: 18px; }}
    .findings li {{ margin: 6px 0; }}
    .table-wrap {{ overflow-x: auto; }}
    table {{ width: 100%; border-collapse: collapse; min-width: 760px; }}
    th, td {{ padding: 10px 12px; border-bottom: 1px solid var(--line); text-align: right; }}
    th:first-child, td:first-child {{ text-align: left; }}
    th {{ color: var(--muted); font-size: 12px; text-transform: uppercase; background: #f9fafb; }}
    tr:hover td {{ background: #f9fafb; }}
    .good {{ color: var(--good); }}
    .bad {{ color: var(--bad); }}
    .neutral {{ color: var(--muted); }}
    details {{ margin-top: 16px; }}
    summary {{ cursor: pointer; color: var(--muted); }}
    pre {{
      overflow-x: auto;
      padding: 14px;
      background: #111827;
      color: #e5e7eb;
      border-radius: 8px;
      font-size: 12px;
    }}
    @media (max-width: 860px) {{
      main {{ padding: 22px 14px 36px; }}
      .cards {{ grid-template-columns: repeat(2, minmax(0, 1fr)); }}
      .card strong {{ font-size: 18px; overflow-wrap: anywhere; }}
    }}
    @media (max-width: 560px) {{
      .cards {{ grid-template-columns: 1fr; }}
    }}
  </style>
</head>
<body>
  <main>
    <header>
      <h1>packet_parser - rapport verbench</h1>
      <p>Source: <code>{esc(input_path)}</code> - genere le {esc(generated_at)}.</p>
    </header>

    {summary_cards(rows)}

    <section class="panel">
      {line_chart(rows, ("total_ns",), "Temps total moyen par version (ns)")}
    </section>

    <section class="panel">
      {line_chart(rows, LAYERS, "Temps moyen par couche OSI (ns)")}
    </section>

    <section class="panel">
      {delta_chart(rows)}
    </section>

    {findings(rows)}
    {result_table(rows)}

    <details>
      <summary>JSON embarque</summary>
      <pre>{esc(raw_json)}</pre>
    </details>
  </main>
</body>
</html>
"""


def main() -> None:
    args = parse_args()
    input_path = Path(args.input).resolve() if args.input else default_input_path()
    output_path = Path(args.output).resolve() if args.output else derived_output_path(input_path)

    rows = load_results(input_path)
    if not rows:
        raise SystemExit("no versions found in input JSON")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_html(rows, input_path), encoding="utf-8")
    print(f"HTML report written to {output_path}")


if __name__ == "__main__":
    main()
