name: Coverage

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  coverage:
    name: Compute Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Tarpaulin
        run: cargo install cargo-tarpaulin

      - name: Run Coverage
        run: cargo tarpaulin --verbose --timeout 120 --out Lcov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./lcov.info

      - name: Trigger publish workflow
        if: success()
        run: gh workflow run publish.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
